services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: Mangazone
    env_file:
      - .env
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=postgres;Username=postgres.mruxtgnyueiermswvmzn;Password=${DB_PASSWORD}
      - ASPNETCORE_URLS=http://+:8080
      - Minio__Endpoint=minio:9000
      - Minio__PublicEndpoint=localhost:9004
      - Minio__UseSSL=false
    depends_on:
      database:
        condition: service_healthy
    networks:
      - Mangazone-networks
    restart: unless-stopped

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres.mruxtgnyueiermswvmzn
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Cinebook -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - Mangazone-networks

  minio:
    image: minio/minio:latest
    container_name: Mangazone-minio
    ports:
      - "9004:9000"
      - "9005:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - minio-data:/data
    networks:
      - Mangazone-networks
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data:

networks:
  Mangazone-networks:
    driver: bridge
